spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/blacklist
    username: postgres
    password: hartono7213
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL81Dialect
        format_sql: true
